---
title: "CSMRL Simulation Accuracy Script 20221024"
author: "Dan Conroy-Beam"
date: "2022-10-24"
output: html_document
---


#####Packages######
```{r}
library(foreach)
library(doParallel)

```






######Population Data######
```{r}

#Load in the population data
data<-read.csv("Model Outputs/Couple Populations/CSMRL Couple Population 20221114 163104.csv")

#Rearrange into pairs
pairs<-cbind(data[data$sex==0,],data[data$sex==1,])

#Extract the models to be tested
models<-sort(unique(data$model))
```






######Parameters######
```{r}

#Model loops#
#How many samples will be drawn from the population
samples<-1:100



#Sample Size#
#The size of the samples to be drawn from the population
sizes<-500



#Perceptual Noise#
#Noise in perception of potential mates
noisePerc<-.5



#UCB Constant#
#Controls degree of exploration for the reciprocal UCB strategy
cRecip<-.2



#Thompson SD#
#Starting SD for Reciprocity-Weighted Thompson sampling (RWTS)
tRecipSD<-.25



#Epsilon#
#Probability of exploration for the reciprocal Epsilon Greedy strategy
eRegret<-.15



#Number of Observations#
#Total number of observation opportunities agents will have in mate search
nobs<-(sizes*30)/5



#Creating a file to save results (if necessary)
mrPath<-"Model Outputs/Simulation Accuracy/CSMRL Simulation Accuracy Results.csv"

if(file.exists(mrPath)==F){
    mRepro<-data.frame("dt"=NA,"modelLoop"=NA,"model"=NA,"n"=NA,"nl"=NA,"recip"=NA,"ucb"=NA)
    
    write.csv(mRepro,mrPath,row.names=F)

}



#Number of Cores#
#Number of CPU cores to use for the parallel loop
clust<-makeCluster(detectCores()-4)
registerDoParallel(clust)
```






######Functions######

```{r}

#Attraction calculation#
mvCalc<-function(ideal,traits){
  #ideal is ideal preferences
  #traits is actual trait values
  
  #Calculates Euclidean distance between preferences and traits
  #Transforms this distance such that positive values are more attractive 
  mv<-apply(traits,1,function(x) 
    (-1*(dist(rbind(ideal,x)))+sqrt(10^2*16))/sqrt(10^2*16))
  
  return(mv)
  
}



#Improved Sampling#
#A sample function that will return a single scalar if given it
resample <- function(x,...){if(length(x)==1) x else sample(x,...)} 

```






######Model Start######
```{r}

#Repeats the entire model based on theparameters set above
mRepro<-foreach(s = samples,.combine=rbind) %dopar% {

  #Create dataframe to store model results
  mRepro<-data.frame("dt"=NA,
                     "modelLoop"=s,
                     "model"=rep(models,length(sizes)),
                     "n"=rep(sizes,
                             each=length(models)),
                     "nl"=0,
                     "recip"=0,
                     "ucb"=0)
  
  #Loop through sample sizes
  for(n in sizes){
    
    #Loop through the models
    for(m in (1:length(models))){
      
      ###Draw Sample###
      
      #Select just the pairs the correspond to the current model of mate choice
      mpairs<-pairs[pairs$model==models[m],]
      
      #Draw a random sample of couples from these pairs
      sample<-mpairs[sample(nrow(mpairs),n,replace=F),]
      
      #Break into females and males
      females<-sample[,1:37]
      males<-sample[,38:74]
      
      #Determine the true relationships in this sample
      trueRels<-cbind(females$PIN,males$PIN)
      colnames(trueRels)<-c("female","male")
      
      
      
      ###MV Calculation###
      
      #Males
      #Calculate the true mate value of each female to each male
      maleAttMatrix<-t(apply(males,1,function(q)
        mvCalc(as.numeric(q[2:17]),females[,c(18:33)])))
      
      #Label these for ease of use
      colnames(maleAttMatrix)<-females$PIN
      rownames(maleAttMatrix)<-males$PIN
      
      #Females
      #Calculate the true mate value of each male to each female
      femaleAttMatrix<-t(apply(females,1,function(q)
        mvCalc(as.numeric(q[2:17]),males[,c(18:33)]))) 
      
      #Label these for ease of use
      colnames(femaleAttMatrix)<-males$PIN
      rownames(femaleAttMatrix)<-females$PIN
      
      #Determine the amount of noise to add to MV perceptions
      noise<-mean(c(var(c(maleAttMatrix)),
                    var(c(femaleAttMatrix))))*
        (noisePerc/(1-noisePerc))
      
      
      
      ###Learning Preparation###
      
      #Create dataframes to store learned attraction values
      eRecipLearnMale<-matrix(1,nrow(males),nrow(females))
      eRecipLearnFemale<-matrix(1,nrow(females),nrow(males))
      
      uRecipLearnMale<-matrix(1,nrow(males),nrow(females))
      uRecipLearnFemale<-matrix(1,nrow(females),nrow(males))
      
      tRecipLearnMale<-matrix(1,nrow(males),nrow(females))
      tRecipLearnFemale<-matrix(1,nrow(females),nrow(males))
      
      tRecipSDMale<-matrix(tRecipSD,nrow(males),nrow(females))
      tRecipSDFemale<-matrix(tRecipSD,nrow(females),nrow(males))
      
      
      #Generate dataframes to store the number of visits
      eRecipInvestMale<-matrix(1,nrow(males),nrow(females))
      eRecipInvestFemale<-matrix(1,nrow(females),nrow(males))
      
      uRecipInvestMale<-matrix(1,nrow(males),nrow(females))
      uRecipInvestFemale<-matrix(1,nrow(females),nrow(males))
      
      tRecipInvestMale<-matrix(1,nrow(males),nrow(females))
      tRecipInvestFemale<-matrix(1,nrow(females),nrow(males))
      
      
      #Generate matrices to track history of reciprocity for RWTS
      eRecipHistMale<-matrix(1,nrow(males),nrow(females))
      eRecipHistFemale<-matrix(1,nrow(females),nrow(males))
      
      uRecipHistMale<-matrix(1,nrow(males),nrow(females))
      uRecipHistFemale<-matrix(1,nrow(females),nrow(males))
      
      tRecipHistMale<-matrix(1,nrow(males),nrow(females))
      tRecipHistFemale<-matrix(1,nrow(females),nrow(males))
      
      
      
      ###Learning Trials#
      
      #Loop through observation opportunities        
      for(o in 1:nobs){
    
        #Reciprocal Epsilon Greedy#
        
        #With probability 1-epsilon...
        if(rbinom(1,1,(1-eRegret))){
          
          #Compute reward as the product of learned MV and history of reciprocity
          eRecipRewardMale<-eRecipLearnMale*eRecipHistMale
          eRecipRewardFemale<-eRecipLearnFemale*eRecipHistFemale
          
          #Choose the most rewarding option in light of this adjustment
          choiceMale<-cbind(1:nrow(males),
                            apply(eRecipRewardMale,1,function(x)
                              resample(which(x==max(x)),1)))
          
          choiceFemale<-cbind(1:nrow(females),
                              apply(eRecipRewardFemale,1,function(x)
                                resample(which(x==max(x)),1)))
        
        } else {
        
          #Otherwise, chose a mate to observe at random
          choiceMale<-cbind(1:nrow(males),
                            sample(1:nrow(females)))
          choiceFemale<-cbind(1:nrow(females),
                              sample(1:nrow(males)))
          
        }
        
        #Update learned MV with a noisy observation of chosen partners
        eRecipLearnMale[choiceMale]<-(eRecipLearnMale[choiceMale]*
                                        eRecipInvestMale[choiceMale]+
                                      5*rnorm(nrow(choiceMale),
                                            maleAttMatrix[choiceMale],
                                            sqrt(noise/5)))/
          (eRecipInvestMale[choiceMale]+5)
        
        eRecipLearnFemale[choiceFemale]<-(eRecipLearnFemale[choiceFemale]*
                                            eRecipInvestFemale[choiceFemale]+
                                          5*rnorm(nrow(choiceFemale),
                                            femaleAttMatrix[choiceFemale],
                                            sqrt(noise/5)))/
          (eRecipInvestFemale[choiceFemale]+5)
        
        #Update observation counts
        eRecipInvestMale[choiceMale]<-eRecipInvestMale[choiceMale]+5
        eRecipInvestFemale[choiceFemale]<-eRecipInvestFemale[choiceFemale]+5
    
        #Update reciprocity histories
        eRecipHistMale<-(t(eRecipInvestFemale)/eRecipInvestMale)
        eRecipHistFemale<-(t(eRecipInvestMale)/eRecipInvestFemale)
        
        
        
        
        
        
        #Reciprocal UCB#
        
        #Calculate the constant that will be added to MV values
        #Increases the less frequently a potential mate is observed
        cm<-cRecip*sqrt(log(rowSums(uRecipInvestMale)[1])/uRecipInvestMale)
        cf<-cRecip*sqrt(log(rowSums(uRecipInvestFemale)[1])/uRecipInvestFemale)
        
        #Add constant to perceived MV
        uRecipRewardMale<-uRecipLearnMale+cm
        uRecipRewardFemale<-uRecipLearnFemale+cf
        
        #Choose the most rewarding option, weighted by reciprocity
        choiceMale<-cbind(1:nrow(males),
                          apply(uRecipRewardMale*
                                  uRecipHistMale,1,function(x)
                            resample(which(x==max(x)),1)))
        
        choiceFemale<-cbind(1:nrow(females),
                            apply(uRecipRewardFemale*
                                    uRecipHistFemale,1,function(x)
                              resample(which(x==max(x)),1)))
        
        #Update learned MV with a noisy observation of chosen partners
        uRecipLearnMale[choiceMale]<-(uRecipLearnMale[choiceMale]*
                                        uRecipInvestMale[choiceMale]+
                                      5*rnorm(nrow(choiceMale),
                                            maleAttMatrix[choiceMale],
                                            sqrt(noise/5)))/
          (uRecipInvestMale[choiceMale]+5)
        
        uRecipLearnFemale[choiceFemale]<-(uRecipLearnFemale[choiceFemale]*
                                            uRecipInvestFemale[choiceFemale]+
                                          5*rnorm(nrow(choiceFemale),
                                            femaleAttMatrix[choiceFemale],
                                            sqrt(noise/5)))/
          (uRecipInvestFemale[choiceFemale]+5)
        
        #Update observation counts
        uRecipInvestMale[choiceMale]<-uRecipInvestMale[choiceMale]+5
        uRecipInvestFemale[choiceFemale]<-uRecipInvestFemale[choiceFemale]+5
        
        #Update reciprocity histories
        uRecipHistMale<-(t(uRecipInvestFemale)/uRecipInvestMale)
        uRecipHistFemale<-(t(uRecipInvestMale)/uRecipInvestFemale)
          
        
        
        
        
        
        #Reciprocal Thompson Sampling#
        
        #Draw a random MV value from each agent's prior distribution
        tRecipDrawMale<-matrix(rnorm(length(tRecipLearnMale),
                                     tRecipLearnMale,
                                     tRecipSDMale),
                              nrow(maleAttMatrix),
                              ncol(maleAttMatrix))
        
        tRecipDrawFemale<-matrix(rnorm(length(tRecipLearnFemale),
                                       tRecipLearnFemale,
                                       tRecipSDFemale),
                                nrow(femaleAttMatrix),
                                ncol(femaleAttMatrix))
        
        #Choose the partner with the highest MV belief, weighted by reciprocity
        choiceMale<-cbind(1:nrow(males),
                          apply(tRecipDrawMale*tRecipHistMale,1,function(x) 
                            resample(which(x==max(x)),1)))
        
        choiceFemale<-cbind(1:nrow(females),
                            apply(tRecipDrawFemale*tRecipHistFemale,1,function(x) 
                              resample(which(x==max(x)),1)))
        
        #Update the mean of agents' MV prior distributions
        tRecipLearnMale[choiceMale]<-(noise/5*tRecipLearnMale[choiceMale]+
                                      (tRecipSDMale[choiceMale]^2)*
                                      rnorm(nrow(choiceMale),
                                            maleAttMatrix[choiceMale],
                                            sqrt(noise/5)))/
          (noise/5+(tRecipSDMale[choiceMale]^2))
        
        tRecipLearnFemale[choiceFemale]<-(noise/5*tRecipLearnFemale[choiceFemale]+
                                      (tRecipSDFemale[choiceFemale]^2)*
                                      rnorm(nrow(choiceFemale),
                                            femaleAttMatrix[choiceFemale],
                                            sqrt(noise/5)))/
          (noise/5+(tRecipSDFemale[choiceFemale]^2))
        
        #And update the standard deviation of the prior distribution
        tRecipSDMale[choiceMale]<-sqrt((noise/5*tRecipSDMale[choiceMale]^2)/
                                       (noise/5+tRecipSDMale[choiceMale]^2))
        tRecipSDFemale[choiceFemale]<-sqrt((noise/5*tRecipSDFemale[choiceFemale]^2)/
                                           (noise/5+tRecipSDFemale[choiceFemale]^2))
        
        #Update observation counts
        tRecipInvestMale[choiceMale]<-tRecipInvestMale[choiceMale]+5
        tRecipInvestFemale[choiceFemale]<-tRecipInvestFemale[choiceFemale]+5
        
        #Update reciprocity histories
        tRecipHistMale<-(t(tRecipInvestFemale)/tRecipInvestMale)
        tRecipHistFemale<-(t(tRecipInvestMale)/tRecipInvestFemale)
        
      
      }
        
      
      
      ###Mate Choice###
      
      #Reciprocal Epsilon Greedy Mate Choice#
      
      #A blank dataframe for storing the paired couples
      eRecipPairs<-matrix(,1,(ncol(males)+ncol(females)))
      eRecipPairs<-as.data.frame(eRecipPairs)
      
      #Name the eRecipPairs dataframe for cbinding
      colnames(eRecipPairs)<-c(colnames(females),colnames(males))
      
      #Determine which female each male has chosen
      #Break ties randomly
      mChoice<-data.frame("male"=1:nrow(males))
      mChoice$choice<-apply(eRecipInvestMale,1,function(x)
        resample(which(x==max(x)),1))
      
      #Determine which male each female has chosen
      #Break ties randomly
      fChoice<-data.frame("female"=1:nrow(females))
      fChoice$choice<-apply(eRecipInvestFemale,1,function(x)
        resample(which(x==max(x)),1))
      
      #Loop through females' choices
      for(p in 1:nrow(fChoice)){
        
        #Determine the male chosen by the current focal female
        chosenMale<-fChoice$choice[p]
        
        #Determine the female chosen by the focal female's choice
        chosenFemale<-mChoice$choice[chosenMale]
        
        #If the chosen female is the focal female...
        if(chosenFemale==p){
          #Pair the male and female together
          eRecipPairs<-rbind(eRecipPairs,cbind(females[p,],males[chosenMale,]))
        }
        
        #Otherwise do nothing
        
      }
      
      #Remove the row of NAs from the eRecipPairs dataframe
      eRecipPairs<-eRecipPairs[-1,]
      
      
      
      
      
      
      #Reciprocal UCB Mate Choice#
      
      #A blank dataframe for storing the paired couples
      uRecipPairs<-matrix(,1,(ncol(males)+ncol(females)))
      uRecipPairs<-as.data.frame(uRecipPairs)
      
      #Name the uRecipPairs dataframe for cbinding
      colnames(uRecipPairs)<-c(colnames(females),colnames(males))
      
      #Determine which female each male has chosen
      #Break ties randomly
      mChoice<-data.frame("male"=1:nrow(males))
      mChoice$choice<-apply(uRecipInvestMale,1,function(x)
        resample(which(x==max(x)),1))
      
      #Determine which male each female has chosen
      #Break ties randomly
      fChoice<-data.frame("female"=1:nrow(females))
      fChoice$choice<-apply(uRecipInvestFemale,1,function(x)
        resample(which(x==max(x)),1))
      
      #Loop through females' choices
      for(p in 1:nrow(fChoice)){
        
        #Determine the male chosen by the current focal female
        chosenMale<-fChoice$choice[p]
        
        #Determine the female chosen by the focal female's choice
        chosenFemale<-mChoice$choice[chosenMale]
        
        #If the chosen female is the focal female...
        if(chosenFemale==p){
          #Pair the male and female together
          uRecipPairs<-rbind(uRecipPairs,cbind(females[p,],males[chosenMale,]))
        }
        
        #Otherwise do nothing
        
      }
      
      #Remove the row of NAs from the uRecipPairs dataframe
      uRecipPairs<-uRecipPairs[-1,]
      
      
      
      
      
      
      #Reciprocal Thompson Mate Choice#
      
      #A blank dataframe for storing the paired couples
      tRecipPairs<-matrix(,1,(ncol(males)+ncol(females)))
      tRecipPairs<-as.data.frame(tRecipPairs)
      
      #Name the tRecipPairs dataframe for cbinding
      colnames(tRecipPairs)<-c(colnames(females),colnames(males))
      
      #Determine which female each male has chosen
      #Break ties randomly
      mChoice<-data.frame("male"=1:nrow(males))
      mChoice$choice<-apply(tRecipInvestMale,1,function(x)
        resample(which(x==max(x)),1))
      
      #Determine which male each female has chosen
      #Break ties randomly
      fChoice<-data.frame("female"=1:nrow(females))
      fChoice$choice<-apply(tRecipInvestFemale,1,function(x)
        resample(which(x==max(x)),1))
      
      #Loop through females' choices
      for(p in 1:nrow(fChoice)){
        
        #Determine the male chosen by the current focal female
        chosenMale<-fChoice$choice[p]
        
        #Determine the female chosen by the focal female's choice
        chosenFemale<-mChoice$choice[chosenMale]
        
        #If the chosen female is the focal female...
        if(chosenFemale==p){
          #Pair the male and female together
          tRecipPairs<-rbind(tRecipPairs,cbind(females[p,],males[chosenMale,]))
        }
        
        #Otherwise do nothing
        
      }
      
      #Remove the row of NAs from the tRecipPairs dataframe
      tRecipPairs<-tRecipPairs[-1,]
      
      
      
      ###Calculating Couple Simulation Accuracy###
      
      #Determine the PINs of all guessed pairs
      eRecipRels<-data.frame("females"=eRecipPairs[,34],"males"=eRecipPairs[,71])
      tRecipRels<-data.frame("females"=tRecipPairs[,34],"males"=tRecipPairs[,71])
      uRecipRels<-data.frame("females"=uRecipPairs[,34],"males"=uRecipPairs[,71])



      #Store the mate guessed by each model for each agent for females
      females$eRecipGuess<-eRecipRels$males[match(females$PIN,eRecipRels$females)]
      females$tRecipGuess<-tRecipRels$males[match(females$PIN,tRecipRels$females)]
      females$uRecipGuess<-uRecipRels$males[match(females$PIN,uRecipRels$females)]

      

      #Do the same for males
      males$eRecipGuess<-eRecipRels$females[match(males$PIN,eRecipRels$males)]
      males$tRecipGuess<-tRecipRels$females[match(males$PIN,tRecipRels$males)]
      males$uRecipGuess<-uRecipRels$females[match(males$PIN,uRecipRels$males)]

      

      #Calculate the accuracy of guesses for females
      females$eRecipAcc<-ifelse(is.na(females$eRecipGuess)==F,females$eRecipGuess==females$mPIN,F)
      females$tRecipAcc<-ifelse(is.na(females$tRecipGuess)==F,females$tRecipGuess==females$mPIN,F)
      females$uRecipAcc<-ifelse(is.na(females$uRecipGuess)==F,females$uRecipGuess==females$mPIN,F)


      #Save results to mRepro in the appropriate spot
      mRepro[mRepro$model==models[m] & mRepro$n==n,5:7]<-colMeans(females[,41:43],na.rm=T)
      mRepro$dt[mRepro$model==models[m] & mRepro$n==n]<-format(Sys.time(),format="%m%d%Y %H%M%S")
      
    }
    
  }
  
  #Output mRepro for storing by the foreach() loop
  mRepro
  
}
  
write.table(mRepro,file=mrPath,append=T,sep=",",row.names=F,col.names=F)

stopCluster(clust)

```

