---
title: "CSMRL Population Generation Script 20221024"
author: "Dan Conroy-Beam"
date: "2022-10-24"
output: html_document
---






######Parameters######
```{r}

#Group Size#
#Determines the size of the subgroups agents will be sorted into
gsize<-1000



#N groups#
ngroups<-50



#Population size#
#Determines the starting and maximum population size of the model
popsize<-gsize*ngroups



#UCB Constant#
#Controls degree of exploration for the reciprocal UCB strategy
cRecip<-.2



#Thompson SD#
#Starting SD for Reciprocity-Weighted Thompson sampling (RWTS)
tRecipSD<-.25



#Epsilon#
#Probability of exploration for the reciprocal Epsilon Greedy strategy
eRegret<-.15



#Number of Observations#
#Total number of observation opportunities agents will have in mate search
#Observations are grouped into 5s to accelerate model runtimes
nobs<-((gsize/2)*30)/5



#Human Data#
#Load in the human data for parameterizing agents
hdata<-read.csv(file="Human Data/Processed Data/CAREER1 PROCESSED Data 01172020 104258.csv")



#Perceptual Noise#
#Noise in perception 
noisePerc<-.50

```







######Functions######
```{r}

#Agent generation#
agentGenerate<-function(popsize,sex,data){
  
  #Generate agents with trait and preferences by resampling from the human data
  agents<-apply(data[,c(10:41)],2,function(x) sample(x,popsize,replace=T))
  
  #Standardize ratings
  agents<-t(apply(agents,2,scale))
  
  #Create a copy of the human dataframe including just the required variables 
  hdata1<-data[,c(10:41)]
  
  #Calculates the correlation matrix for traits and preferences in the real data
  hdata1cor<-cor(hdata1)
  
  #Computes the Cholesky decomposition of this matrix
  #This will impose a realistic covariance matrix on the simulated data
  hdata1chol<-t(chol(hdata1cor))
  
  #Multiplies the scaled agent data by the Cholesky decomposition
  #This imposes approximately the correct covariance matrix
  agents<-t(hdata1chol %*% agents)
  
  #Add the mean of each variable to the simulated data to re-center data
  agents<-sapply(1:ncol(agents),function(x)
    (sd(hdata1[,x])*agents[,x])+mean(hdata1[,x]))
  
  
  #Truncate rated variables to the true mini and max found in the human data
  agents<-sapply(1:ncol(agents),function(x) 
    ifelse(agents[,x]>max(hdata1[,x]),max(hdata1[,x]),agents[,x]))
  
  agents<-sapply(1:ncol(agents),function(x) 
    ifelse(agents[,x]<min(hdata1[,x]),min(hdata1[,x]),agents[,x]))
  
  #Names variables appropriately
  colnames(agents)<-colnames(hdata1)
  
  return(as.data.frame(cbind(sex,agents)))
}



#Attraction calculation#
mvCalc<-function(ideal,traits){
  #ideal is ideal preferences
  #traits is actual trait values
  
  #Calculates Euclidean distance between preferences and traits
  #Transforms this distance such that positive values are more attractive 
  mv<-apply(traits,1,function(x) 
    (-1*(dist(rbind(ideal,x)))+sqrt(10^2*16))/sqrt(10^2*16))
  
  return(mv)
  
}




#Improved Sampling#
#A sample function that will return a single scalar if given it
resample <- function(x,...){if(length(x)==1) x else sample(x,...)} 

```






######Agent Generation######
```{r}

#Remove unnecessary columns from the human data
hdata<-hdata[,c(1,3:10,235:250,345:360)]

#Make sure there's no missing information
hdata<-hdata[complete.cases(hdata[,c(10:41)]),]

#Generate agents
males<-agentGenerate(popsize/2,1,hdata[hdata$sex==1,])
females<-agentGenerate(popsize/2,0,hdata[hdata$sex==0,])

#Give each agent a unique PIN
males$PIN<-sample(1:nrow(males),nrow(males),replace=F)
females$PIN<-sample(nrow(males):(nrow(males)+nrow(females)),nrow(females),replace=F)

#Assign each male and female to a random population subgroup
males$group<-sample(rep(1:ngroups,gsize/4))
females$group<-sample(rep(1:ngroups,gsize/4))

```



######Learning and Mate Choice######

```{r}

#Blank dataframes for storing couples paired by different models of mate choice

#First generate one dataframe
popPairs<-matrix(,1,(ncol(males)+ncol(females)))

#Name the pairs dataframe for cbinding
colnames(popPairs)<-c(colnames(females),colnames(males))

#Pre-generate a dataframe for storing all final couples
data<-males[-(1:nrow(males)),]

#Generate each model-specific dataframe by copying from the larger dataframe
eRecipPairs<-popPairs
uRecipPairs<-popPairs
tRecipPairs<-popPairs

for(r in 1:ngroups){
  
  #Identify the agents in this group
  malesg<-males[males$group==r,]
  femalesg<-females[females$group==r,]
  
  
  
  ###MV Calculation###
  
  #Males
  #Calculate the true mate value of each female to each male
  maleAttMatrix<-t(apply(malesg,1,function(q)
    mvCalc(as.numeric(q[2:17]),femalesg[,c(18:33)])))
  
  #Label these for ease of use
  colnames(maleAttMatrix)<-femalesg$PIN
  rownames(maleAttMatrix)<-malesg$PIN
  
  #Females
  #Calculate the true mate value of each male to each female
  femaleAttMatrix<-t(apply(femalesg,1,function(q)
    mvCalc(as.numeric(q[2:17]),malesg[,c(18:33)]))) 
  
  #Label these for ease of use
  colnames(femaleAttMatrix)<-malesg$PIN
  rownames(femaleAttMatrix)<-femalesg$PIN
  
  #Determine the amount of noise to add to MV perceptions
  noise<-mean(c(var(c(maleAttMatrix)),
                var(c(femaleAttMatrix))))*
    (noisePerc/(1-noisePerc))
  
  
  
  ###Learning Preparation###
  
  #Create dataframes to store learned attraction values
  eRecipLearnMale<-matrix(1,nrow(malesg),nrow(femalesg))
  eRecipLearnFemale<-matrix(1,nrow(femalesg),nrow(malesg))
  
  uRecipLearnMale<-matrix(1,nrow(malesg),nrow(femalesg))
  uRecipLearnFemale<-matrix(1,nrow(femalesg),nrow(malesg))
  
  tRecipLearnMale<-matrix(1,nrow(malesg),nrow(femalesg))
  tRecipLearnFemale<-matrix(1,nrow(femalesg),nrow(malesg))
  
  tRecipSDMale<-matrix(tRecipSD,nrow(malesg),nrow(femalesg))
  tRecipSDFemale<-matrix(tRecipSD,nrow(femalesg),nrow(malesg))
  
  
  #Generate dataframes to store the number of visits
  eRecipInvestMale<-matrix(1,nrow(malesg),nrow(femalesg))
  eRecipInvestFemale<-matrix(1,nrow(femalesg),nrow(malesg))
  
  uRecipInvestMale<-matrix(1,nrow(malesg),nrow(femalesg))
  uRecipInvestFemale<-matrix(1,nrow(femalesg),nrow(malesg))
  
  tRecipInvestMale<-matrix(1,nrow(malesg),nrow(femalesg))
  tRecipInvestFemale<-matrix(1,nrow(femalesg),nrow(malesg))
  
  
  #Generate matrices to track history of reciprocity for RWTS
  eRecipHistMale<-matrix(1,nrow(malesg),nrow(femalesg))
  eRecipHistFemale<-matrix(1,nrow(femalesg),nrow(malesg))
  
  uRecipHistMale<-matrix(1,nrow(malesg),nrow(femalesg))
  uRecipHistFemale<-matrix(1,nrow(femalesg),nrow(malesg))
  
  tRecipHistMale<-matrix(1,nrow(malesg),nrow(femalesg))
  tRecipHistFemale<-matrix(1,nrow(femalesg),nrow(malesg))
  
  
  
  ###Learning Trials#
  
  #Loop through observation opportunities        
  for(o in 1:nobs){

    #Reciprocal Epsilon Greedy#
    
    #With probability 1-epsilon...
    if(rbinom(1,1,(1-eRegret))){
      
      #Compute reward as the product of learned MV and history of reciprocity
      eRecipRewardMale<-eRecipLearnMale*eRecipHistMale
      eRecipRewardFemale<-eRecipLearnFemale*eRecipHistFemale
      
      #Choose the most rewarding option in light of this adjustment
      choiceMale<-cbind(1:nrow(malesg),
                        apply(eRecipRewardMale,1,function(x)
                          resample(which(x==max(x)),1)))
      
      choiceFemale<-cbind(1:nrow(femalesg),
                          apply(eRecipRewardFemale,1,function(x)
                            resample(which(x==max(x)),1)))
    
    } else {
    
      #Otherwise, chose a mate to observe at random
      choiceMale<-cbind(1:nrow(malesg),
                        sample(1:nrow(femalesg)))
      choiceFemale<-cbind(1:nrow(femalesg),
                          sample(1:nrow(malesg)))
      
    }
    
    #Update learned MV with a noisy observation of chosen partners
    eRecipLearnMale[choiceMale]<-(eRecipLearnMale[choiceMale]*
                                    eRecipInvestMale[choiceMale]+
                                  5*rnorm(nrow(choiceMale),
                                        maleAttMatrix[choiceMale],
                                        sqrt(noise/5)))/
      (eRecipInvestMale[choiceMale]+5)
    
    eRecipLearnFemale[choiceFemale]<-(eRecipLearnFemale[choiceFemale]*
                                        eRecipInvestFemale[choiceFemale]+
                                      5*rnorm(nrow(choiceFemale),
                                        femaleAttMatrix[choiceFemale],
                                        sqrt(noise/5)))/
      (eRecipInvestFemale[choiceFemale]+5)
    
    #Update observation counts
    eRecipInvestMale[choiceMale]<-eRecipInvestMale[choiceMale]+5
    eRecipInvestFemale[choiceFemale]<-eRecipInvestFemale[choiceFemale]+5

    #Update reciprocity histories
    eRecipHistMale<-(t(eRecipInvestFemale)/eRecipInvestMale)
    eRecipHistFemale<-(t(eRecipInvestMale)/eRecipInvestFemale)
    
    
    
    
    
    
    #Reciprocal UCB#
    
    #Calculate the constant that will be added to MV values
    #Increases the less frequently a potential mate is observed
    cm<-cRecip*sqrt(log(rowSums(uRecipInvestMale)[1])/uRecipInvestMale)
    cf<-cRecip*sqrt(log(rowSums(uRecipInvestFemale)[1])/uRecipInvestFemale)
    
    #Add constant to perceived MV
    uRecipRewardMale<-uRecipLearnMale+cm
    uRecipRewardFemale<-uRecipLearnFemale+cf
    
    #Choose the most rewarding option, weighted by reciprocity
    choiceMale<-cbind(1:nrow(malesg),
                      apply(uRecipRewardMale*
                              uRecipHistMale,1,function(x)
                        resample(which(x==max(x)),1)))
    
    choiceFemale<-cbind(1:nrow(femalesg),
                        apply(uRecipRewardFemale*
                                uRecipHistFemale,1,function(x)
                          resample(which(x==max(x)),1)))
    
    #Update learned MV with a noisy observation of chosen partners
    uRecipLearnMale[choiceMale]<-(uRecipLearnMale[choiceMale]*
                                    uRecipInvestMale[choiceMale]+
                                  5*rnorm(nrow(choiceMale),
                                        maleAttMatrix[choiceMale],
                                        sqrt(noise/5)))/
      (uRecipInvestMale[choiceMale]+5)
    
    uRecipLearnFemale[choiceFemale]<-(uRecipLearnFemale[choiceFemale]*
                                        uRecipInvestFemale[choiceFemale]+
                                      5*rnorm(nrow(choiceFemale),
                                        femaleAttMatrix[choiceFemale],
                                        sqrt(noise/5)))/
      (uRecipInvestFemale[choiceFemale]+5)
    
    #Update observation counts
    uRecipInvestMale[choiceMale]<-uRecipInvestMale[choiceMale]+5
    uRecipInvestFemale[choiceFemale]<-uRecipInvestFemale[choiceFemale]+5
    
    #Update reciprocity histories
    uRecipHistMale<-(t(uRecipInvestFemale)/uRecipInvestMale)
    uRecipHistFemale<-(t(uRecipInvestMale)/uRecipInvestFemale)
      
    
    
    
    
    
    #Reciprocal Thompson Sampling#
    
    #Draw a random MV value from each agent's prior distribution
    tRecipDrawMale<-matrix(rnorm(length(tRecipLearnMale),
                                 tRecipLearnMale,
                                 tRecipSDMale),
                          nrow(maleAttMatrix),
                          ncol(maleAttMatrix))
    
    tRecipDrawFemale<-matrix(rnorm(length(tRecipLearnFemale),
                                   tRecipLearnFemale,
                                   tRecipSDFemale),
                            nrow(femaleAttMatrix),
                            ncol(femaleAttMatrix))
    
    #Choose the partner with the highest MV belief, weighted by reciprocity
    choiceMale<-cbind(1:nrow(malesg),
                      apply(tRecipDrawMale*tRecipHistMale,1,function(x) 
                        resample(which(x==max(x)),1)))
    
    choiceFemale<-cbind(1:nrow(femalesg),
                        apply(tRecipDrawFemale*tRecipHistFemale,1,function(x) 
                          resample(which(x==max(x)),1)))
    
    #Update the mean of agents' MV prior distributions
    tRecipLearnMale[choiceMale]<-(noise/5*tRecipLearnMale[choiceMale]+
                                  (tRecipSDMale[choiceMale]^2)*
                                  rnorm(nrow(choiceMale),
                                        maleAttMatrix[choiceMale],
                                        sqrt(noise/5)))/
      (noise/5+(tRecipSDMale[choiceMale]^2))
    
    tRecipLearnFemale[choiceFemale]<-(noise/5*tRecipLearnFemale[choiceFemale]+
                                  (tRecipSDFemale[choiceFemale]^2)*
                                  rnorm(nrow(choiceFemale),
                                        femaleAttMatrix[choiceFemale],
                                        sqrt(noise/5)))/
      (noise/5+(tRecipSDFemale[choiceFemale]^2))
    
    #And update the standard deviation of the prior distribution
    tRecipSDMale[choiceMale]<-sqrt((noise/5*tRecipSDMale[choiceMale]^2)/
                                   (noise/5+tRecipSDMale[choiceMale]^2))
    tRecipSDFemale[choiceFemale]<-sqrt((noise/5*tRecipSDFemale[choiceFemale]^2)/
                                       (noise/5+tRecipSDFemale[choiceFemale]^2))
    
    #Update observation counts
    tRecipInvestMale[choiceMale]<-tRecipInvestMale[choiceMale]+5
    tRecipInvestFemale[choiceFemale]<-tRecipInvestFemale[choiceFemale]+5
    
    #Update reciprocity histories
    tRecipHistMale<-(t(tRecipInvestFemale)/tRecipInvestMale)
    tRecipHistFemale<-(t(tRecipInvestMale)/tRecipInvestFemale)
    
  
  }
    
  
  
  ###Mate Choice###
  
  #Reciprocal Epsilon Greedy Mate Choice#
  
  #A blank dataframe for storing the paired couples
  eRecipGpairs<-matrix(,1,(ncol(malesg)+ncol(femalesg)))
  eRecipGpairs<-as.data.frame(eRecipGpairs)
  
  #Name the eRecipGpairs dataframe for cbinding
  colnames(eRecipGpairs)<-c(colnames(femalesg),colnames(malesg))
  
  #Determine which female each male has chosen
  #Break ties randomly
  mChoice<-data.frame("male"=1:nrow(malesg))
  mChoice$choice<-apply(eRecipInvestMale,1,function(x)
    resample(which(x==max(x)),1))
  
  #Determine which male each female has chosen
  #Break ties randomly
  fChoice<-data.frame("female"=1:nrow(femalesg))
  fChoice$choice<-apply(eRecipInvestFemale,1,function(x)
    resample(which(x==max(x)),1))
  
  #Loop through femalesg' choices
  for(p in 1:nrow(fChoice)){
    
    #Determine the male chosen by the current focal female
    chosenMale<-fChoice$choice[p]
    
    #Determine the female chosen by the focal female's choice
    chosenFemale<-mChoice$choice[chosenMale]
    
    #If the chosen female is the focal female...
    if(chosenFemale==p){
      #Pair the male and female together
      eRecipGpairs<-rbind(eRecipGpairs,cbind(femalesg[p,],malesg[chosenMale,]))
    }
    
    #Otherwise do nothing
    
  }
  
  #Remove the row of NAs from the eRecipGpairs dataframe
  eRecipGpairs<-eRecipGpairs[-1,]
  
  
  
  
  
  
  #Reciprocal UCB Mate Choice#
  
  #A blank dataframe for storing the paired couples
  uRecipGpairs<-matrix(,1,(ncol(malesg)+ncol(femalesg)))
  uRecipGpairs<-as.data.frame(uRecipGpairs)
  
  #Name the uRecipGpairs dataframe for cbinding
  colnames(uRecipGpairs)<-c(colnames(femalesg),colnames(malesg))
  
  #Determine which female each male has chosen
  #Break ties randomly
  mChoice<-data.frame("male"=1:nrow(malesg))
  mChoice$choice<-apply(uRecipInvestMale,1,function(x)
    resample(which(x==max(x)),1))
  
  #Determine which male each female has chosen
  #Break ties randomly
  fChoice<-data.frame("female"=1:nrow(femalesg))
  fChoice$choice<-apply(uRecipInvestFemale,1,function(x)
    resample(which(x==max(x)),1))
  
  #Loop through femalesg' choices
  for(p in 1:nrow(fChoice)){
    
    #Determine the male chosen by the current focal female
    chosenMale<-fChoice$choice[p]
    
    #Determine the female chosen by the focal female's choice
    chosenFemale<-mChoice$choice[chosenMale]
    
    #If the chosen female is the focal female...
    if(chosenFemale==p){
      #Pair the male and female together
      uRecipGpairs<-rbind(uRecipGpairs,cbind(femalesg[p,],malesg[chosenMale,]))
    }
    
    #Otherwise do nothing
    
  }
  
  #Remove the row of NAs from the uRecipGpairs dataframe
  uRecipGpairs<-uRecipGpairs[-1,]
  
  
  
  
  
  
  #Reciprocal Thompson Mate Choice#
  
  #A blank dataframe for storing the paired couples
  tRecipGpairs<-matrix(,1,(ncol(malesg)+ncol(femalesg)))
  tRecipGpairs<-as.data.frame(tRecipGpairs)
  
  #Name the tRecipGpairs dataframe for cbinding
  colnames(tRecipGpairs)<-c(colnames(femalesg),colnames(malesg))
  
  #Determine which female each male has chosen
  #Break ties randomly
  mChoice<-data.frame("male"=1:nrow(malesg))
  mChoice$choice<-apply(tRecipInvestMale,1,function(x)
    resample(which(x==max(x)),1))
  
  #Determine which male each female has chosen
  #Break ties randomly
  fChoice<-data.frame("female"=1:nrow(femalesg))
  fChoice$choice<-apply(tRecipInvestFemale,1,function(x)
    resample(which(x==max(x)),1))
  
  #Loop through femalesg' choices
  for(p in 1:nrow(fChoice)){
    
    #Determine the male chosen by the current focal female
    chosenMale<-fChoice$choice[p]
    
    #Determine the female chosen by the focal female's choice
    chosenFemale<-mChoice$choice[chosenMale]
    
    #If the chosen female is the focal female...
    if(chosenFemale==p){
      #Pair the male and female together
      tRecipGpairs<-rbind(tRecipGpairs,cbind(femalesg[p,],malesg[chosenMale,]))
    }
    
    #Otherwise do nothing
    
  }
  
  #Remove the row of NAs from the tRecipGpairs dataframe
  tRecipGpairs<-tRecipGpairs[-1,]
  
  
  
  #Rbind each group's couples into the population couples dataframes
  eRecipPairs<-rbind(eRecipPairs,eRecipGpairs)
  uRecipPairs<-rbind(uRecipPairs,uRecipGpairs)
  tRecipPairs<-rbind(tRecipPairs,tRecipGpairs)
  
}



#Remove the unnecessary NAs from each pairs dataframe
eRecipPairs<-eRecipPairs[-1,]
uRecipPairs<-uRecipPairs[-1,]
tRecipPairs<-tRecipPairs[-1,]



#Split each pairs dataframe into males and females
eRecipDataF<-eRecipPairs[,1:35]
eRecipDataM<-eRecipPairs[,36:70]

uRecipDataF<-uRecipPairs[,1:35]
uRecipDataM<-uRecipPairs[,36:70]

tRecipDataF<-tRecipPairs[,1:35]
tRecipDataM<-tRecipPairs[,36:70]



#Store the PINs of each agents' mates
eRecipDataF$mPIN<-eRecipDataM$PIN
eRecipDataM$mPIN<-eRecipDataF$PIN

uRecipDataF$mPIN<-uRecipDataM$PIN
uRecipDataM$mPIN<-uRecipDataF$PIN

tRecipDataF$mPIN<-tRecipDataM$PIN
tRecipDataM$mPIN<-tRecipDataF$PIN



#Store the integration model responsible for each couple
eRecipDataF$model<-"eRecip"
eRecipDataM$model<-"eRecip"

uRecipDataF$model<-"uRecip"
uRecipDataM$model<-"uRecip"

tRecipDataF$model<-"tRecip"
tRecipDataM$model<-"tRecip"



#Put all the couple populations together into one dataframe
data<-rbind(data,
            eRecipDataF,
            eRecipDataM,
            uRecipDataF,
            uRecipDataM,
            tRecipDataF,
            tRecipDataM)





#Create a unique filename so the model can output results without overwriting old results.
#Name format is "Euclidean Couple Population MonthDayYear HourMinuteSecond"
#This filepath will need to be made specific to your computer.
path<-"Model Outputs/Couple Populations/CSMRL Couple Population "

format<-".csv"
date<-format(Sys.time(),format="%Y%m%d %H%M%S")
file<-file.path(paste0(path,date,format))

write.csv(data,file=file,row.names=F)


```